[rule."/ref[@name='ostype']/element[@name='os_type'][1]/choice[1]"]
parent_is_this = true

[rule."/ref[@name='wordsize']/element[@name='wordsize'][1]/choice[1]"]
parent_is_this = true

[rule."/ref[@name='migration']/element[@name='migration_features'][1]/group[1]/optional/element[@name='uri_transports'][1]/oneOrMore/element[@name='uri_transport'][1]/choice[1]"]
parent_is_this = true
